[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gpumarket = "EVCyQThJVQXsYFTqHsU4rUg84CshcV69kG8QNakgCcKo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/projects/sol/backend/wallet/keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
