[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gpumarket = "DPQG3BiR9Avg5mknQTDKZ24w4T9D8NEKmgALvEyyH2N4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./programs/gpumarket/wallet/new_program-keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
